# Generated by Django 5.0.3 on 2024-03-31 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Input",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("value", models.CharField(max_length=200)),
                ("subsystem", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Output",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("value", models.CharField(max_length=200)),
                ("subsystem", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="InputLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=200)),
                ("time", models.DateTimeField(auto_now_add=True)),
                (
                    "name",
                    models.ForeignKey(
                        db_column="name",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="mqtt.input",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OutputLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=200)),
                ("time", models.DateTimeField(auto_now_add=True)),
                (
                    "name",
                    models.ForeignKey(
                        db_column="name",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="mqtt.output",
                    ),
                ),
            ],
        ),
    ]
