# Generated by Django 5.0.3 on 2024-03-31 07:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mqtt", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="outputlog",
            name="name",
        ),
        migrations.DeleteModel(
            name="Output",
        ),
        migrations.DeleteModel(
            name="OutputLog",
        ),
    ]
