# Generated by Django 5.0.3 on 2024-03-31 08:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mqtt", "0002_remove_outputlog_name_delete_output_delete_outputlog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="input",
            name="subsystem",
        ),
    ]
