# Generated by Django 5.0.3 on 2024-03-31 08:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mqtt", "0003_remove_input_subsystem"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Input",
            new_name="Robot",
        ),
        migrations.RenameModel(
            old_name="InputLog",
            new_name="RobotLog",
        ),
    ]
